### ISSUE TITLE
Update Failed gives a percentage

### ISSUE THREAD

**Issue by SquidDev** [dan200/IndieLauncher#1]
On line 52 of `Dan200.Launcher.Interface.WinForms.UpdateForm`:

``` C#
this.Text = stage.GetStatus( Program.Language ) + " (" + percentage + "%)";
```

The trouble is that some `GameUpdateStage`s (`NotStarted`, `Finished`, `Cancelled` and `Failed`) really don't need percentages and so should probably be hidden on the WinForms title bar.

My best solution is to add another extension method to `GameUpdateStageExtensions` called `ShowPercentage` that would choose if it should show the percentage for that Stage - otherwise `Update Failed (100%)` sounds silly (can I get `Update Failed (90%)`?). [Like this](https://github.com/SquidDev/IndieLauncher/commit/7c6984e7c0a7bea20bc554d537d095c3c4795011) because code paints a thousand words.

Sorry for this really pedantic change at night but I'm like that. :smile:

**Comment by dan200** [comment]
A reasonable request. Fixed in latest. I have two questions though:
1) Would you mind sending me some screenshots of the GUI? I haven't seen it running on Windows
2) Did you actually see "Update Failed", and if so: what was the circumstance?

**Comment by SquidDev** [comment]
![choice](https://cloud.githubusercontent.com/assets/4346137/3848763/eb86b32c-1e72-11e4-97fd-28c8008d362c.png)
![downloading](https://cloud.githubusercontent.com/assets/4346137/3848764/eb8867ee-1e72-11e4-9f4b-16f3c74f19b8.png)
![installing](https://cloud.githubusercontent.com/assets/4346137/3848765/eb8fd696-1e72-11e4-98fc-b199f12e1963.png)
![launching](https://cloud.githubusercontent.com/assets/4346137/3848766/eb91fb7e-1e72-11e4-8986-9b8ae549297b.png)
Don't know if this is what you wanted... You could use WPF to make it look pretty but its fine for what it does.

I was getting an update failed before https://github.com/dan200/IndieLauncher/commit/c90ab5802decf1383adbe30093f39dbd14eb2307 and changed it back to see what happened.

**Comment by dan200** [comment]
Looks good enough to me :)
